TOPDIR := $(realpath ../..)

CLEAN-FILES := data/pilka.c data/cube.c

LIBS := lib3d

OBJ2C.pilka := --scale 65.0 --mesh-name pilka
OBJ2C.cube := --scale 40.0 --mesh-name cube

include $(TOPDIR)/build/effect.mk
